### ISSUE TITLE
How to use -f flag correctly?

### ISSUE THREAD

**Issue by nabusch** [cdaven/noteexplorer#1]
Thanks a lot for providing this tool! It is actually tremendously helpful for maintaining my Zettelkasten! I just cannot figure out how to use the `-f` flag to force the file rename and suppress the confirmation. The documentation says:

> Asks for confirmation for each rename, unless you specify the flag -f last in the command.

However, when I use the flag like so:

```.\noteexplorer --backlinks-heading "## Backlinks"  ./Zettelkasten update-filenames -f```

I get this error message:

error: Found argument '-f' which wasn't expected, or isn't valid in this context

USAGE:
    noteexplorer.exe update-filenames
    
Moving the -f flag around to other locations in the call to noteexplorer didn't help either. Could you please elaborate how to use the -f flag correctly?

I am using noteexplorer-win-x64-0.2.1 on Windows 10.

**Comment by cdaven** [comment]
Sorry about that! I never got around to releasing 0.3.0, which is where this flag was introduced.

Please download and try 0.3.0: https://github.com/cdaven/noteexplorer/releases/tag/0.3.0
