### ISSUE TITLE
backlink not created

### ISSUE THREAD

**Issue by gour** [cdaven/noteexplorer#2]
Hello,

 I'm still deciding which note-taking application to use...one of the strongest candidate is [nb](https://github.com/xwmx/nb) which currently uses [note-link-janitor](https://github.com/andymatuschak/note-link-janitor) script, but for me your tool should be superior and I [mentioned](https://github.com/xwmx/nb/issues/14#issuecomment-938590569) it as potential replacement.

Besides `nb` I am also considering [Joplin](https://joplinapp.org/) as well as combination of [vimwiki](https://github.com/vimwiki/vimwiki) and [taskwiki](https://github.com/tools-life/taskwiki) being an user of [taskwarrior](https://github.com/GothenburgBitFactory/taskwarrior). :smile: 

However, I've some problem with your tool - picked [sample](https://github.com/Zettelkasten-Method/10000-markdown-files) suite and played with it a bit, but I'm getting strange results.

Here I picked just two files and created one link, but `notexplorer` does not create backlink.
[test.tar.gz](https://github.com/cdaven/noteexplorer/files/7317145/test.tar.gz)

Any hint what might be wrong?

(I have tried with both YAL front-matter as well as with `Heading 1`, but no luck...)

**Comment by cdaven** [comment]
The wikilink in your example uses the target note's title, but you must use the filename or an ID. The reason for this is that it's easy to create multiple notes with identical titles, but not identical filenames.

See here: https://github.com/cdaven/noteexplorer#limitationsrules

For this reason, there is a command to rename the files based on the title or ID: https://github.com/cdaven/noteexplorer#update-filenames
