### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by jbirch** [cdaven/noteexplorer#4]
It would be fantastically convenient if `noteexplorer` were published on crates.io, allowing people to install with `cargo install noteexplorer` or similar.

I appreciate I'm asking to add some further packaging and deployment concerns on top of your responsibilities, for what is ostensibly only removing "git clone" or "going over to the 'downloads' tab" for consumers — I won't feel hard done by if this isn't a thing you're interested in doing :)

Thanks for `noteexplorer`!

**Comment by cdaven** [comment]
Thanks for your suggestion. There are many ways to distribute applications, and I currently don't have the time or motivation to publish to crates.io.

I will close this issue, since I'm not going to do anything about it, but I understand that it would be useful to some.
